include:
  - environment.basic
  - environment.locale
  - environment.timezone
  - environment.hostname
  - environment.certbot
  - environment.sshd
  - environment.users
  - environment.netshares
  - environment.zabbix-agent
  - environment.shorewall
